version: "3.8"

services:
  web-search:
    #    image: registry.cn-hangzhou.aliyuncs.com/aasee-share/open-web-search:latest # China region
    image: ghcr.io/aas-ee/open-web-search:latest
    container_name: web-search
    working_dir: /app
    restart: unless-stopped
    ports:
      - "3000:3000"
    #    extra_hosts:
    #      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      # DEFAULT_SEARCH_ENGINE: "brave" # Optional: 'bing' | 'duckduckgo' | 'brave', default brave (Note: Bing currently has issues) (optional)
      # USE_PROXY: true # Using a proxy (optional)
      # PROXY_URL: "http://host.docker.internal:7890"  #  Using a proxy (optional)
      ENABLE_CORS: "true"
      CORS_ORIGIN: "*" # Multiple values can be separated by commas and parsed accordingly
    command: ["bun", "src/index.ts"]
